# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### Send POST request with json body
POST http://localhost:8001/trade-info/validate
Content-Type: application/json

{
    "customer":"PLUTO1",
    "ccyPair":"EURUSD",
    "type":"Spot",
    "direction":"BUY",
    "tradeDate":"2016-08-11",
    "amount1":1000000.00,
    "amount2":1120000.00,
    "rate":1.12,
    "valueDate":"2016-08-15",
    "legalEntity":"CS Zurich",
    "trader":"Johann Baumfiddler"
}
###